name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [main] }

jobs:
  linux-integration:
    permissions:
      contents: read
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    container: swift:6.3-noble
    steps:
      - name: Check out JWTKit
        uses: actions/checkout@v7
        with:
          path: jwt-kit
      - name: Check out JWT provider
        uses: actions/checkout@v7
        with:
          repository: vapor/jwt
          path: jwt
      - name: Use local JWTKit
        run: swift package --package-path jwt edit jwt-kit --path ./jwt-kit
      - name: Run tests with Thread Sanitizer
        run: swift test --package-path jwt --sanitize=thread

  unit-tests:
    permissions:
      contents: read
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    secrets: inherit
    with:
      with_musl: true
      with_android: true
      with_linting: true
      with_windows: true
      # Re-enable when SwiftCrypto builds on WASM
      # with_wasm: true
      ios_scheme_name: jwt-kit

  submit-dependencies:
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' }}
    uses: vapor/ci/.github/workflows/submit-deps.yml@main
    secrets: inherit

  foundation-linking:
    uses: vapor/ci/.github/workflows/check-foundation-linking.yml@727bb2695c01ea0876b91d1ba2ee139c0a0f64f7
    permissions:
      contents: read
    with:
      swift_image: swift:6.3-noble
